### ISSUE TITLE
Any idea if this still works?

### ISSUE THREAD

**Issue by devn** [jimm/erlang-midilib#1]
I'm getting into Elixir and would love to play with MIDI. Does this work anymore? If not, what could be done to fix it?

**Comment by jimm** [comment]
@devn, I'm very sorry that I didn't see this issue until now. I think that midifile should still work, but I haven't been playing with Erlang for a while. See https://github.com/jimm/elixir-midifile for the Elixir version of this library. As far as I know that is still working. The `mix test` tests still pass :-)
